app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');

Route::get('/player', 'HomeController@player');

Route::get('/article/select', ['uses' => 'ArticleController@selectDate']);

Route::get('/article/{id}', ['as' => 'article', 'uses' => 'ArticleController@index']);

Route::get('/category/{id}', ['as' => 'category', 'uses' => 'CategoryController@index']);

Route::get('/tag/{id}', ['as' => 'tag', 'uses' => 'TagController@index']);

Route::get('/search', ['as' => 'search', 'uses' => 'SearchController@index']);

Route::get('/page/{alias}', ['as' => 'page.show', 'uses' => 'PageController@index']);

Route::get('/about',['as'=>'about','uses'=>'PageController@about']);

Route::get('/mail','ArticleController@mail');

Route::post('/comment',['as'=>'comment','uses'=>'CommentController@store']);

Route::get('/send',['as'=>'send','uses'=>'CommentController@send']);


Route::group(['prefix' => 'backend'], function () {

    Route::get('/login', 'Backend\AuthController@showLoginForm');

    Route::post('/login', 'Backend\AuthController@login');

    Route::get('/logout', 'Backend\AuthController@logout');

    Route::group(['middleware' => ['auth']], function () {

        Route::get('/', ['as' => 'backend.home', 'uses' => 'Backend\HomeController@index']);

        Route::get('mini-index', ['as' => 'backend.article.mini-index', 'uses' => 'Backend\ArticleController@miniIndex']);

        Route::get('mini-create', ['as' => 'backend.article.mini-create', 'uses' => 'Backend\ArticleController@miniArticleCreate']);

        Route::post('mini-store', ['as' => 'backend.article.mini-store', 'uses' => 'Backend\ArticleController@miniArticleStore']);

        Route::get('mini-edit/{id}', ['as' => 'backend.article.mini-edit', 'uses' => 'Backend\ArticleController@miniArticleEdit']);

        Route::post('mini-update/{id}',['as' => 'backend.article.mini-update','uses'=>'Backend\ArticleController@miniArticleUpdate']);

        Route::delete('mini-destroy/{id}',['as' => 'backend.article.mini-destroy','uses'=>'Backend\ArticleController@miniArticleDestroy']);

        Route::resource('article', 'Backend\ArticleController');

        Route::get('comment-index', ['as' => 'backend.comment.mini-index', 'uses' => 'Backend\CommentController@miniIndex']);

        Route::delete('comment-destroy/{id}', ['as' => 'backend.comment.mini-destroy', 'uses' => 'Backend\CommentController@miniDestroy']);

        Route::resource('comment','Backend\CommentController');

        Route::get('category-index', ['as' => 'backend.category.category-index', 'uses' => 'Backend\CategoryController@miniCategoryIndex']);

        Route::get('category-create', ['as' => 'backend.category.category-create', 'uses' => 'Backend\CategoryController@miniCategoryCreate']);

        Route::post('category-store', ['as' => 'backend.category.category-store', 'uses' => 'Backend\CategoryController@miniCategoryStore']);

        Route::get('category-edit/{id}', ['as' => 'backend.category.category-edit', 'uses' => 'Backend\CategoryController@miniCategoryEdit']);

        Route::post('category-update/{id}', ['as' => 'backend.category.category-update', 'uses' => 'Backend\CategoryController@miniCategoryUpdate']);

        Route::delete('category-destroy/{id}', ['as' => 'backend.category.category-destroy', 'uses' => 'Backend\CategoryController@miniCategoryDestroy']);

        Route::resource('category', 'Backend\CategoryController');

        Route::get('category/set-nav/{id}', ['as' => 'backend.category.set-nav', 'uses' => 'Backend\CategoryController@setNavigation']);

        Route::get('user-index', ['as' => 'backend.user.user-index', 'uses' => 'Backend\UserController@miniUserIndex']);

        Route::delete('user-destroy/{id}', ['as' => 'backend.user.user-destroy', 'uses' => 'Backend\UserController@miniUserDestroy']);

        Route::get('sign-index', ['as' => 'backend.user.sign-index', 'uses' => 'Backend\UserController@miniSignIndex']);

        Route::resource('user', 'Backend\UserController');

        Route::resource('tag', 'Backend\TagController');

        Route::resource('link', 'Backend\LinkController');

        Route::resource('navigation', 'Backend\NavigationController');

        Route::get('upload', ['as' => 'backend.upload.index', 'uses' => 'Backend\UploadController@index']);

        Route::resource('page', 'Backend\PageController');

        Route::get('system', ['as' => 'backend.system.index', 'uses' => 'Backend\SystemController@index']);

        Route::post('system', ['as' => 'backend.system.store', 'uses' => 'Backend\SystemController@store']);

        Route::get('upload', ['as' => 'backend.upload.index', 'uses' => 'Backend\UploadController@index']);

        Route::delete('file-del', ['as' => 'backend.upload.file-del', 'uses' => 'Backend\UploadController@fileDelete']);

        Route::delete('dir-del', ['as' => 'backend.upload.dir-del', 'uses' => 'Backend\UploadController@dirDelete']);

        Route::post('mkdir', ['as' => 'backend.upload.mkdir', 'uses' => 'Backend\UploadController@makeDir']);

        Route::get('file-upload', ['as' => 'backend.upload.file-upload', 'uses' => 'Backend\UploadController@fileUpload']);

        Route::post('uploadimage',['uses'=>'Backend\UploadController@uploadimage']);

        Route::post('file-store', ['as' => 'backend.upload.file-store', 'uses' => 'Backend\UploadController@fileStore']);
    });
});

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Backend\Article\CreateRequest;
use App\Http\Requests\Backend\Article\UpdateRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\ArticleService;
use BmobObject;
use Auth;

class ArticleController extends Controller
{

    /**
     * @var ArticleService
     */
    protected $articleServer;
    protected $BmobObj;

    /**
     * ArticleController constructor.
     * @param ArticleService $articleService
     */
    public function __construct(ArticleService $articleService)
    {
        $this->articleServer = $articleService;
        $show = config('mini.show');
        if ($show) {
            $this->BmobObj = new BmobObject("articles");
        }
    }

    /**
     * 文章列表
     * Display a listing of the articles
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $articles = $this->articleServer->search($request);
        return view('backend.article.index', compact('articles'));
    }

    /**
     * 新建文章--表单
     * Show the form for creating a new article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backend.article.create');
    }

    /**
     * Store a new article
     * @param CreateRequest $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        return $this->articleServer->store($request);
    }

    /**
     * Show the form for updating the article
     * @param $id
     * @return $this
     */
    public function edit($id)
    {
        return view('backend.article.edit')->with($this->articleServer->edit($id));
    }

    /**
     * Update the article by id
     * @param UpdateRequest $request
     * @param $id
     * @return mixed
     */
    public function update(UpdateRequest $request, $id)
    {
        return $this->articleServer->update($request, $id);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        return $this->articleServer->destroy($id);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function miniIndex()
    {
        $result = $this->BmobObj->get("", array('include=category.name', 'order=-createdAt'));
        $articles = $result->results;
        return view('backend.article.mini_index', compact('articles'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function miniArticleCreate()
    {
        $BmobObj = new BmobObject("categories");
        $result = $BmobObj->get();
        $select = "<select id='category' name='category' class='form-control'>";
        $select .= "<option value='0'>--请选择--</option>";
        foreach ($result->results as $key => $value) {
            $selected = $value->objectId == 1 ? "selected" : "";
            $select .= "<option value='" . $value->objectId . "' " . $selected . ">" . $value->name . "</option>";
        }
        $select .= "</select>";
        return view('backend.article.mini_create',compact('select'));
    }


    /**
     * @param Request $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function miniArticleStore(Request $request)
    {
        $res=$this->BmobObj->addRelPointer(array(array("category","categories",$request->get('category'))));
        $res=$this->BmobObj->update($res->objectId,array(
            "title"=>$request->get('title'),
            "read_counts"=>(int)$request->get('read_counts'),
            "excerpt"=>$request->get('excerpt'),
            "author"=>$request->get('author'),
            "content"=>$request->get('html-content'),
            "mdcontent"=>$request->get('markdown-content')
        ));
        if (!$res) {
            return redirect()->back()->withErrors('系统异常，文章发布失败');
        }
        return redirect('backend/mini-index')->with('success', '文章添加成功');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function miniArticleEdit($id)
    {
        $article = $this->BmobObj->get($id, array('include=category.name'));

        $BmobObj = new BmobObject("categories");
        $result = $BmobObj->get();
        $select = "<select id='category' name='category' class='form-control'>";
        $select .= "<option value='0'>--请选择--</option>";
        foreach ($result->results as $key => $value) {
            $selected = $value->objectId == $article->category->objectId ? "selected" : "";
            $select .= "<option value='" . $value->objectId . "' " . $selected . ">" . $value->name . "</option>";
        }
        $select .= "</select>";

        return view('backend.article.mini_edit',compact('article','select'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function miniArticleUpdate(Request $request,$id)
    {
        $res = $this->BmobObj->updateRelPointer($id,"category","categories",$request->category);
        $res = $this->BmobObj->update($id,array(
            "title"=>$request->get('title'),
            "read_counts"=>(int)$request->get('read_counts'),
            "excerpt"=>$request->get('excerpt'),
            "author"=>$request->get('author'),
            "content"=>$request->get('html-content'),
            "mdcontent"=>$request->get('markdown-content')
        ));
        if (!$res) {
            return redirect()->back()->withErrors('系统异常，文章修改失败');
        }
        return redirect('backend/mini-index')->with('success', '文章修改成功');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function miniArticleDestroy($id)
    {
        $res = $this->BmobObj->delete($id);
        if(!$res){
            return response()->json([
                'status' => 1
            ]);
        }
        return response()->json(['status' => 0]);

    }


}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use App\User;
use Validator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;

class AuthController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Registration & Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users, as well as the
    | authentication of existing users. By default, this controller uses
    | a simple trait to add these behaviors. Why don't you explore it?
    |
    */

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    //protected $redirectTo = '/';
    protected $redirectTo = '/backend';
    protected $loginView = 'backend.login';

    /**
     * Create a new authentication controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware($this->guestMiddleware(), ['except' => 'logout']);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
            'captcha' => 'required|captcha',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }

    /**
     * @param Request $request
     */
    protected function validateLogin(Request $request){
        $this->validate($request, [
            $this->loginUsername() => 'required',
            'password' => 'required',
            'captcha' => 'required|captcha',
        ]);
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use App\Repositories\CommentRepositoryEloquent;
use Illuminate\Http\Request;
use BmobObject;
use App\Common\CustomPage;

class CommentController extends Controller
{

    /**
     * CommentController constructor.
     * @param CommentRepositoryEloquent $comment
     */
    public function __construct(CommentRepositoryEloquent $comment)
    {
        $this->comment=$comment;
        $show = config('mini.show');
        if ($show) {
            $this->BmobObj = new BmobObject("comments");
        }
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $comments=$this->comment->orderBy('id', 'desc')->paginate('15');
        return view('backend.comment.index',compact('comments'));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        if($this->comment->delete($id)) {
            return response()->json(['status' => 0]);
        }
        return response()->json(['status' => 1]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function miniIndex(Request $request)
    {
        $pageSize = 20;//每页条数
        if ($request->get('nowPage')) {
            $nowPage = $request->get('nowPage');//当前页码
        } else {
            $nowPage = 1;
        }

        $res = $this->BmobObj->get("", array('groupcount=true', 'groupby=createdAt' . 'order=-createdAt'));
        $count = $res->results[0]->_count;//总条数
        $countPage = ceil($count / $pageSize);//总页数
        $pages = CustomPage::getSelfPageView($nowPage, $countPage, '/backend/comment-index');
        $skip = ($nowPage-1)*$pageSize;
        $res = $this->BmobObj->get("",array("limit=$pageSize","skip=$skip",'order=-createdAt','include=replyer,user'));

        $comments = $res->results;

        return view('backend.comment.mini_index',compact("pages","comments","count"));
    }

    public function miniDestroy($id)
    {
        $res = $this->BmobObj->delete($id);
        if(!$res){
            return response()->json([
                'status' => 1
            ]);
        }
        return response()->json(['status' => 0]);
    }

}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        return view('backend.home');
    }
}

resources/views/backend/page/create.blade.php
@extends('layouts.backend')

@section('title', '新建页面')

@section('stylesheet')
    <link rel="stylesheet" href="{{ asset('editor.md/css/editormd.min.css') }}">
@endsection

@section('header')
    <h1>
        新建页面
    </h1>
@endsection

@section('content')
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            @include('backend.alert.warning')
            <div class="box box-solid">
                <form role="form" method="post" action="{{ url('backend/page') }}" id="page-form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="title">页面标题</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' class='form-control' name="title" id='title' placeholder='标题'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="link_alias">链接别名</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' class='form-control' name="link_alias" id='link_alias' placeholder='链接别名,关于页面请用about关联'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="keyword">关键字(Keywords)</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' class='form-control' name="keyword" id='keyword' placeholder='请输入关键字，以英文逗号分割，利于搜索引擎收录'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="desc">描述(Description)</label>
                            <div class="row">
                                <div class='col-md-10'>
                                    <input type='text' class='form-control' name="desc" id='desc' placeholder='请输入页面描述'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="content">页面内容</label>
                            <div id="editormd">
                                <textarea class="editormd-markdown-textarea" style="display:none;" id="content" name="content"></textarea>
                                <textarea style="display:none;"  name="html_content"></textarea>
                            </div>
                        </div>
                    </div>

                    {{ csrf_field() }}


                    <div class="box-footer">
                        <button type="submit" id="submit-page" class="btn btn-primary">创建</button>
                        <button type="button" id="reset-btn" class="btn btn-warning">重置</button>
                    </div>
                </form>

            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

@section('javascript')
    <script src="{{ asset('editor.md/editormd.min.js') }}"></script>
    <script>

        var editor = editormd("editormd", {
            path        : "{{ asset('/editor.md/lib/') }}/",
            height  : 500,
            syncScrolling : "single",
            toolbarAutoFixed: false,
            saveHTMLToTextarea : false,
            imageUpload: true,
            imageFormats : ["jpg","jpeg","gif","png","bmp","webp"],
            imageUploadURL:"{{url('backend/uploadimage')}}"
        });

        /* 页面操作验证 */
        $("#page-form").bootstrapValidator({
            live: 'disables',
            message: "This Values is not valid",
            feedbackIcons: {
                valid: 'glyphicon ',
                invalid: 'glyphicon ',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields : {
                title : {
                    validators : {
                        notEmpty : {
                            message : "页面标题不能为空"
                        }
                    }
                }
            }
        }).on('success.form.bv', function(e) {
            var html = editor.getPreviewedHTML();
            $("#page-form textarea[name='html_content']").val(html);
        });
    </script>
@endsection

resources/views/backend/page/edit.blade.php
@extends('layouts.backend')

@section('title', '页面修改')

@section('stylesheet')
    <link rel="stylesheet" href="{{ asset('editor.md/css/editormd.min.css') }}">
@endsection

@section('header')
    <h1>
        页面修改
    </h1>
@endsection

@section('content')
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            @include('backend.alert.warning')
            <div class="box box-solid">
                <form role="form" method="post" action="{{ route('backend.page.update', ['id' => $page->id]) }}" id="page-form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="title">页面标题</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' value="{{ $page->title }}" class='form-control' name="title" id='title' placeholder='标题'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="link_alias">链接别名</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' value="{{ $page->link_alias }}" class='form-control' name="link_alias" id='link_alias' placeholder='链接别名,关于页面请用about关联'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="keyword">关键字(Keywords)</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' value="{{ $page->keyword }}" class='form-control' name="keyword" id='keyword' placeholder='请输入关键字，以英文逗号分割，利于搜索引擎收录'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="desc">描述(Description)</label>
                            <div class="row">
                                <div class='col-md-10'>
                                    <input type='text' value="{{ $page->desc }}" class='form-control' name="desc" id='desc' placeholder='请输入页面描述'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="content">页面内容</label>
                            <div id="editormd">
                                <textarea class="editormd-markdown-textarea" style="display:none;" id="content" name="content">{{ $page->content }}</textarea>
                                <textarea style="display:none;"  name="html_content"></textarea>
                            </div>
                        </div>
                    </div>

                    {{ csrf_field() }}
                    {{ method_field('PUT') }}


                    <div class="box-footer">
                        <button type="submit" id="submit-page" class="btn btn-primary">保存</button>
                        <button type="button" id="reset-btn" class="btn btn-warning">重置</button>
                    </div>
                </form>

            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

@section('javascript')
    <script src="{{ asset('editor.md/editormd.min.js') }}"></script>
    <script>

        var editor = editormd("editormd", {
            path        : "{{ asset('/editor.md/lib/') }}/",
            height  : 500,
            syncScrolling : "single",
            toolbarAutoFixed: false,
            saveHTMLToTextarea : false,
            imageUpload: true,
            imageFormats : ["jpg","jpeg","gif","png","bmp","webp"],
            imageUploadURL:"{{url('backend/uploadimage')}}"
        });

        /* 页面操作验证 */
        $("#page-form").bootstrapValidator({
            live: 'disables',
            message: "This Values is not valid",
            feedbackIcons: {
                valid: 'glyphicon ',
                invalid: 'glyphicon ',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields : {
                title : {
                    validators : {
                        notEmpty : {
                            message : "页面标题不能为空"
                        }
                    }
                }
            }
        }).on('success.form.bv', function(e) {
            var html = editor.getPreviewedHTML();
            $("#page-form textarea[name='html_content']").val(html);
        });
    </script>
@endsection

resources/views/backend/page/index.blade.php
@extends('layouts.backend')

@section('title','自定义页面')

@section('header')
    <h1>
        自定义页面管理
    </h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-xs-12">
            @include('backend.alert.success')
            <div class="box box-solid">
                <div class="box-header">
                    <div class="pull-right">
                        <a href='{{ route("backend.page.create") }}' class='btn btn-success btn-xs'>
                            <i class="fa fa-plus"></i>新增页面</a>
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding ">
                    <table class="table table-hover">
                        <tr>
                            <th>标题</th>
                            <th>链接名</th>
                            <th>关键字</th>
                            <th>描述</th>
                            <th>操作</th>
                        </tr>
                        @inject('pagePresenter', 'App\Presenters\PagePresenter')
                        @if($pages)
                            @foreach($pages as $page)
                                <tr>
                                    <td>{{ $page->title }}</td>
                                    <td>{{ $pagePresenter->getLink($page->id, $page->link_alias) }}</td>
                                    <td>{{ $page->keyword }}</td>
                                    <td>{{ $page->desc }}</td>
                                    <td>
                                        <a href='{{ route("backend.page.edit", ["id" => $page->id]) }}' class='btn btn-info btn-xs'>
                                            <i class="fa fa-pencil"></i> 修改</a>
                                        <a data-href='{{ route("backend.page.destroy", ["id" => $page->id]) }}'
                                           class='btn btn-danger btn-xs page-delete'><i class="fa fa-trash-o"></i> 删除</a>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </table>
                </div>
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

@section('javascript')
    <script>
        $(function() {
            $(".page-delete").click(function(){
                var url = $(this).attr('data-href');
                Moell.ajax.delete(url);
            });
        });
    </script>
@endsection